### ISSUE TITLE
初次运行bot.py时出现报错

### ISSUE THREAD

**Issue by beiyaohhhc** [snowyfirefly/Liteyuki-Bot#18]
系统：windows 2019
报错内容Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nonebot\Liteyuki\bot.py", line 20, in <module>
    from src.extraApi.base import ExConfig
  File "C:\Users\Administrator\Desktop\nonebot\Liteyuki\src\extraApi\base.py", line 209, in <module>
    class ExtraData:
  File "C:\Users\Administrator\Desktop\nonebot\Liteyuki\src\extraApi\base.py", line 257, in ExtraData
    async def getTargetCard(bot: Bot, event: GroupMessageEvent | PrivateMessageEvent, user_id=None):
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'ModelMetaclass'

**Comment by beiyaohhhc** [comment]
> 系统：windows server 2019 报错内容Traceback (most recent call last): File "C:\Users\Administrator\Desktop\nonebot\Liteyuki\bot.py", line 20, in from src.extraApi.base import ExConfig File "C:\Users\Administrator\Desktop\nonebot\Liteyuki\src\extraApi\base.py", line 209, in class ExtraData: File "C:\Users\Administrator\Desktop\nonebot\Liteyuki\src\extraApi\base.py", line 257, in ExtraData async def getTargetCard(bot: Bot, event: GroupMessageEvent | PrivateMessageEvent, user_id=None): TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'ModelMetaclass'
